name: Mirror repository

# Required secrets:
# OV_SOURCE_REPOSITORY_PAT_READ_REPO - Personal access token which can be used to access private repositories

# Required variables:
# OV_SOURCE_ORGANIZATION - Organization of source repositories

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GIT_USERNAME: 'ov-automation'
  GIT_EMAIL: 'github-actions@github.com'
  OLD_REPOSITORY_DIR_NAME: old-repository.git

jobs:
  mirror_repository:
    name: Mirror repository
    runs-on: ubuntu-latest
    if: vars.OV_SOURCE_ORGANIZATION != null 
      && vars.OV_SOURCE_ORGANIZATION != ''
      && github.repository_owner != vars.OV_SOURCE_ORGANIZATION
    steps:
      - name: Configure Git
        run: |
          git config --replace-all user.name "$GIT_USERNAME"
          git config --replace-all user.email "$GIT_EMAIL"

      - name: Clone source repository
        run: |
          git config --remove-section http.'https://github.com/'
          git config --replace-all url.'https://${{ secrets.OV_SOURCE_REPOSITORY_PAT_READ_REPO }}@github.com'.insteadOf 'https://github.com'
          git clone --bare 'https://github.com/${{ vars.OV_SOURCE_ORGANIZATION }}/${{ github.event.repository.name }}.git' "$OLD_REPOSITORY_DIR_NAME"

      - name: Push to mirror repository
        run: |
          git config --remove-section http.'https://github.com/'
          git config --replace-all url.'https://${{ github.token }}@github.com'.insteadOf 'https://github.com'

          cd "$OLD_REPOSITORY_DIR_NAME"
          git push --mirror '${{ github.event.repository.clone_url }}'
