name: Mirror repository

# Required secrets:
# OV_SOURCE_REPOSITORY_PAT_READ_REPO - Personal access token which can be used to access private repositories

# Required variables:
# OV_SOURCE_ORGANIZATION - Organization of source repositories

on:
  workflow_dispatch:
#  Uncomment to automatically sync the repository on schedule
#  schedule:
#    - cron: "0 0 * * *"

permissions:
  contents: write

env:
  GIT_USERNAME: 'ov-automation'
  GIT_EMAIL: 'github-actions@github.com'
  OLD_REPOSITORY_DIR_NAME: old-repository.git

jobs:
  mirror_repository:
    name: Mirror repository
    runs-on: ubuntu-latest
    if: vars.OV_SOURCE_ORGANIZATION != null && vars.OV_SOURCE_ORGANIZATION != ''
    steps:
      - name: Configure Git
        run: |
          git config --global --replace-all user.name "$GIT_USERNAME"
          git config --global --replace-all user.email "$GIT_EMAIL"

      - name: Clone source repository
        run: git clone --mirror 'https://${{ secrets.OV_SOURCE_REPOSITORY_PAT_READ_REPO }}@github.com/${{ vars.OV_SOURCE_ORGANIZATION }}/${{ github.event.repository.name }}.git' "$OLD_REPOSITORY_DIR_NAME"

      - name: Update mirror repository
        run: |
          cd "$OLD_REPOSITORY_DIR_NAME"
          git push --mirror 'https://token:${{ github.token }}@github.com/${{ github.repository }}.git'
